Data Manipulation and Analysis with pandas

Data manipulation and anlysis are key tasks in any data science or data analysis project. pandas provides a wide range of functions for data manipulation and anlysis, marking it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and anlysis techniques using pandas

In [2]:
import pandas as pd

In [6]:
df=pd.read_csv('data.csv')
## fetch the first 5 rows

df.head(5)

,Dataset,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance,...,JoinDate,Performance,CustomerName,Rating,PaymentMethod,Temperature,Humidity,Rainfall,WindSpeed,Condition
0,STUDENT,1.0,Tanu,21.0,Female,Bangalore,85.0,90.0,78.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,STUDENT,2.0,Bhanu,19.0,Male,Shimoga,72.0,68.0,80.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,STUDENT,3.0,Sanju,23.0,Male,Mysore,90.0,95.0,88.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,STUDENT,4.0,Priya,20.0,Female,Bangalore,65.0,70.0,75.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,STUDENT,5.0,Ravi,22.0,Male,Hubli,55.0,60.0,58.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
import os
print(os.listdir())

['8.1-numpy.ipynb', '8.2-pandas.ipynb', '8.3-datamanipulation.ipynb']

In [5]:
import os
print(os.getcwd())   # shows which folder Python is looking in

c:\python_in_vscode\8.Data Analysis with python

In [7]:
df.tail(5)

,Dataset,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance,...,JoinDate,Performance,CustomerName,Rating,PaymentMethod,Temperature,Humidity,Rainfall,WindSpeed,Condition
25,WEATHER,NaN,NaN,NaN,NaN,Bangalore,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,22.0,75.0,0.0,12.0,Sunny
26,WEATHER,NaN,NaN,NaN,NaN,Mysore,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,20.0,80.0,2.0,8.0,Cloudy
27,WEATHER,NaN,NaN,NaN,NaN,Hubli,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,25.0,65.0,0.0,15.0,Sunny
28,WEATHER,NaN,NaN,NaN,NaN,Bangalore,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,23.0,70.0,5.0,10.0,Rainy
29,WEATHER,NaN,NaN,NaN,NaN,Mysore,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,21.0,78.0,8.0,7.0,Rainy

In [8]:
df.describe()

,StudentID,Age,Math,Science,English,Attendance,OrderID,Quantity,Price,Discount,PatientID,Bill,EmpID,Salary,Experience,Rating,Temperature,Humidity,Rainfall,WindSpeed
count,5.000000,20.00000,5.000000,5.000000,5.000000,5.000000,10.000000,10.000000,10.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,3.000000,28.30000,73.400000,76.600000,75.800000,86.400000,3.000000,2.400000,10655.000000,6.600000,3.000000,25900.000000,3.000000,57400.000000,7.200000,4.300000,22.200000,73.600000,3.000000,10.400000
std,1.581139,10.98372,14.328294,15.093045,11.054411,11.674759,1.490712,1.349897,16982.907257,4.219005,1.581139,31389.488687,1.581139,11238.327278,5.357238,0.469042,1.923538,6.107373,3.464102,3.209361
min,1.000000,19.00000,55.000000,60.000000,58.000000,70.000000,1.000000,1.000000,350.000000,0.000000,1.000000,4500.000000,1.000000,45000.000000,2.000000,3.800000,20.000000,65.000000,0.000000,7.000000
25%,2.000000,21.00000,65.000000,68.000000,75.000000,80.000000,2.000000,1.250000,1275.000000,5.000000,2.000000,5000.000000,2.000000,52000.000000,3.000000,4.000000,21.000000,70.000000,0.000000,8.000000
50%,3.000000,23.00000,72.000000,70.000000,78.000000,88.000000,3.000000,2.000000,2500.000000,8.000000,3.000000,15000.000000,3.000000,55000.000000,6.000000,4.200000,22.000000,75.000000,2.000000,10.000000
75%,4.000000,32.00000,85.000000,90.000000,80.000000,95.000000,4.000000,3.000000,13250.000000,10.000000,4.000000,25000.000000,4.000000,60000.000000,10.000000,4.500000,23.000000,78.000000,5.000000,12.000000
max,5.000000,60.00000,90.000000,95.000000,88.000000,99.000000,5.000000,5.000000,55000.000000,10.000000,5.000000,80000.000000,5.000000,75000.000000,15.000000,5.000000,25.000000,80.000000,8.000000,15.000000

In [9]:
df.dtypes

Dataset              str
StudentID        float64
Name                 str
Age              float64
Gender               str
City                 str
Math             float64
Science          float64
English          float64
Attendance       float64
OrderID          float64
Product              str
Category             str
Quantity         float64
Price            float64
Discount         float64
Date                 str
SalesRep             str
PatientID        float64
Disease              str
Doctor               str
AdmitDate            str
DischargeDate        str
Bill             float64
EmpID            float64
Department           str
Salary           float64
Experience       float64
JoinDate             str
Performance          str
CustomerName         str
Rating           float64
PaymentMethod        str
Temperature      float64
Humidity         float64
Rainfall         float64
WindSpeed        float64
Condition            str
dtype: object

In [13]:
## handling Missing Values

df.isnull().any()

Dataset          False
StudentID         True
Name              True
Age               True
Gender            True
City             False
Math              True
Science           True
English           True
Attendance        True
OrderID           True
Product           True
Category          True
Quantity          True
Price             True
Discount          True
Date              True
SalesRep          True
PatientID         True
Disease           True
Doctor            True
AdmitDate         True
DischargeDate     True
Bill              True
EmpID             True
Department        True
Salary            True
Experience        True
JoinDate          True
Performance       True
CustomerName      True
Rating            True
PaymentMethod     True
Temperature       True
Humidity          True
Rainfall          True
WindSpeed         True
Condition         True
dtype: bool

In [15]:
df.isnull().sum()

Dataset           0
StudentID        25
Name              5
Age              10
Gender           10
City              0
Math             25
Science          25
English          25
Attendance       25
OrderID          20
Product          20
Category         20
Quantity         20
Price            20
Discount         25
Date             15
SalesRep         25
PatientID        25
Disease          25
Doctor           25
AdmitDate        25
DischargeDate    25
Bill             25
EmpID            25
Department       25
Salary           25
Experience       25
JoinDate         25
Performance      25
CustomerName     25
Rating           25
PaymentMethod    25
Temperature      25
Humidity         25
Rainfall         25
WindSpeed        25
Condition        25
dtype: int64

In [21]:
df.fillna(0)

,Dataset,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance,...,JoinDate,Performance,CustomerName,Rating,PaymentMethod,Temperature,Humidity,Rainfall,WindSpeed,Condition
0,STUDENT,1.0,Tanu,21.0,Female,Bangalore,85.0,90.0,78.0,95.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
1,STUDENT,2.0,Bhanu,19.0,Male,Shimoga,72.0,68.0,80.0,88.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
2,STUDENT,3.0,Sanju,23.0,Male,Mysore,90.0,95.0,88.0,99.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
3,STUDENT,4.0,Priya,20.0,Female,Bangalore,65.0,70.0,75.0,80.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
4,STUDENT,5.0,Ravi,22.0,Male,Hubli,55.0,60.0,58.0,70.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
5,SALES,0.0,Ravi,0.0,0,Bangalore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
6,SALES,0.0,Sneha,0.0,0,Mysore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
7,SALES,0.0,Kiran,0.0,0,Hubli,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
8,SALES,0.0,Priya,0.0,0,Bangalore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
9,SALES,0.0,Sneha,0.0,0,Mysore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
10,PATIENT,0.0,Tanu,21.0,Female,Bangalore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
11,PATIENT,0.0,Bhanu,45.0,Male,Mysore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
12,PATIENT,0.0,Sanju,60.0,Male,Hubli,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
13,PATIENT,0.0,Priya,32.0,Female,Bangalore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
14,PATIENT,0.0,Ravi,28.0,Male,Shimoga,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0
15,EMPLOYEE,0.0,Ravi,28.0,Male,Bangalore,0.0,0.0,0.0,0.0,...,2021-06-01,Good,0,0.0,0,0.0,0.0,0.0,0.0,0
16,EMPLOYEE,0.0,Sneha,32.0,Female,Mysore,0.0,0.0,0.0,0.0,...,2018-03-15,Excellent,0,0.0,0,0.0,0.0,0.0,0.0,0
17,EMPLOYEE,0.0,Kiran,45.0,Male,Hubli,0.0,0.0,0.0,0.0,...,2009-07-20,Good,0,0.0,0,0.0,0.0,0.0,0.0,0
18,EMPLOYEE,0.0,Divya,27.0,Female,Bangalore,0.0,0.0,0.0,0.0,...,2022-01-10,Average,0,0.0,0,0.0,0.0,0.0,0.0,0
19,EMPLOYEE,0.0,Arun,38.0,Male,Shimoga,0.0,0.0,0.0,0.0,...,2014-05-25,Excellent,0,0.0,0,0.0,0.0,0.0,0.0,0
20,ECOMMERCE,0.0,Tanu,21.0,Female,Bangalore,0.0,0.0,0.0,0.0,...,0,0,Tanu,4.5,UPI,0.0,0.0,0.0,0.0,0
21,ECOMMERCE,0.0,Bhanu,19.0,Male,Mysore,0.0,0.0,0.0,0.0,...,0,0,Bhanu,4.0,Card,0.0,0.0,0.0,0.0,0
22,ECOMMERCE,0.0,Sanju,23.0,Male,Hubli,0.0,0.0,0.0,0.0,...,0,0,Sanju,5.0,COD,0.0,0.0,0.0,0.0,0
23,ECOMMERCE,0.0,Priya,20.0,Female,Bangalore,0.0,0.0,0.0,0.0,...,0,0,Priya,4.2,UPI,0.0,0.0,0.0,0.0,0
24,ECOMMERCE,0.0,Ravi,22.0,Male,Shimoga,0.0,0.0,0.0,0.0,...,0,0,Ravi,3.8,Card,0.0,0.0,0.0,0.0,0
25,WEATHER,0.0,0,0.0,0,Bangalore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,22.0,75.0,0.0,12.0,Sunny
26,WEATHER,0.0,0,0.0,0,Mysore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,20.0,80.0,2.0,8.0,Cloudy
27,WEATHER,0.0,0,0.0,0,Hubli,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,25.0,65.0,0.0,15.0,Sunny
28,WEATHER,0.0,0,0.0,0,Bangalore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,23.0,70.0,5.0,10.0,Rainy
29,WEATHER,0.0,0,0.0,0,Mysore,0.0,0.0,0.0,0.0,...,0,0,0,0.0,0,21.0,78.0,8.0,7.0,Rainy

In [20]:
df_filled=df.fillna(0)

In [24]:
## filling missing values with the mean of the column

df['Sales_fillNA']=df['Sales'].fillna(df['Sales'].mean())

KeyError: 'Sales'

In [25]:
df.dtypes

Dataset              str
StudentID        float64
Name                 str
Age              float64
Gender               str
City                 str
Math             float64
Science          float64
English          float64
Attendance       float64
OrderID          float64
Product              str
Category             str
Quantity         float64
Price            float64
Discount         float64
Date                 str
SalesRep             str
PatientID        float64
Disease              str
Doctor               str
AdmitDate            str
DischargeDate        str
Bill             float64
EmpID            float64
Department           str
Salary           float64
Experience       float64
JoinDate             str
Performance          str
CustomerName         str
Rating           float64
PaymentMethod        str
Temperature      float64
Humidity         float64
Rainfall         float64
WindSpeed        float64
Condition            str
dtype: object

In [26]:
## Renaming columns

df.rename(columns={'Date':'sale.Date'})
df.head()

,Dataset,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance,...,JoinDate,Performance,CustomerName,Rating,PaymentMethod,Temperature,Humidity,Rainfall,WindSpeed,Condition
0,STUDENT,1.0,Tanu,21.0,Female,Bangalore,85.0,90.0,78.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,STUDENT,2.0,Bhanu,19.0,Male,Shimoga,72.0,68.0,80.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,STUDENT,3.0,Sanju,23.0,Male,Mysore,90.0,95.0,88.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,STUDENT,4.0,Priya,20.0,Female,Bangalore,65.0,70.0,75.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,STUDENT,5.0,Ravi,22.0,Male,Hubli,55.0,60.0,58.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
## change datatypes

df['value_new']=df['value'].fillna(df['value'].mean()).astype(int)
df.head()

KeyError: 'value'

In [29]:
print(df.columns.tolist())

['Dataset', 'StudentID', 'Name', 'Age', 'Gender', 'City', 'Math', 'Science', 'English', 'Attendance', 'OrderID', 'Product', 'Category', 'Quantity', 'Price', 'Discount', 'Date', 'SalesRep', 'PatientID', 'Disease', 'Doctor', 'AdmitDate', 'DischargeDate', 'Bill', 'EmpID', 'Department', 'Salary', 'Experience', 'JoinDate', 'Performance', 'CustomerName', 'Rating', 'PaymentMethod', 'Temperature', 'Humidity', 'Rainfall', 'WindSpeed', 'Condition']

In [31]:
df.columns = df.columns.str.strip()

In [32]:
df['value_new'] = df['value'].fillna(df['value'].mean()).astype(int)
df.head()

KeyError: 'value'

In [33]:
print(df.shape)

(30, 38)

In [34]:
print(df.head())

   Dataset  StudentID   Name   Age  Gender       City  Math  Science  English  \
0  STUDENT        1.0   Tanu  21.0  Female  Bangalore  85.0     90.0     78.0
1  STUDENT        2.0  Bhanu  19.0    Male    Shimoga  72.0     68.0     80.0
2  STUDENT        3.0  Sanju  23.0    Male     Mysore  90.0     95.0     88.0
3  STUDENT        4.0  Priya  20.0  Female  Bangalore  65.0     70.0     75.0
4  STUDENT        5.0   Ravi  22.0    Male      Hubli  55.0     60.0     58.0

   Attendance  ...  JoinDate Performance CustomerName  Rating  PaymentMethod  \
0        95.0  ...       NaN         NaN          NaN     NaN            NaN
1        88.0  ...       NaN         NaN          NaN     NaN            NaN
2        99.0  ...       NaN         NaN          NaN     NaN            NaN
3        80.0  ...       NaN         NaN          NaN     NaN            NaN
4        70.0  ...       NaN         NaN          NaN     NaN            NaN

   Temperature Humidity Rainfall  WindSpeed Condition
0          NaN      NaN      NaN        NaN       NaN
1          NaN      NaN      NaN        NaN       NaN
2          NaN      NaN      NaN        NaN       NaN
3          NaN      NaN      NaN        NaN       NaN
4          NaN      NaN      NaN        NaN       NaN

[5 rows x 38 columns]

In [35]:
# Check which column you actually want
print(df[['Salary', 'Price', 'Rating', 'Math']].head())

   Salary  Price  Rating  Math
0     NaN    NaN     NaN  85.0
1     NaN    NaN     NaN  72.0
2     NaN    NaN     NaN  90.0
3     NaN    NaN     NaN  65.0
4     NaN    NaN     NaN  55.0

In [36]:
# Example: create 'value' from an existing column
df['value'] = df['Salary']  # or any other column

# Then your original code will work
df['value_new'] = df['value'].fillna(df['value'].mean()).astype(int)
df.head()

,Dataset,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance,...,CustomerName,Rating,PaymentMethod,Temperature,Humidity,Rainfall,WindSpeed,Condition,value,value_new
0,STUDENT,1.0,Tanu,21.0,Female,Bangalore,85.0,90.0,78.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400
1,STUDENT,2.0,Bhanu,19.0,Male,Shimoga,72.0,68.0,80.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400
2,STUDENT,3.0,Sanju,23.0,Male,Mysore,90.0,95.0,88.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400
3,STUDENT,4.0,Priya,20.0,Female,Bangalore,65.0,70.0,75.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400
4,STUDENT,5.0,Ravi,22.0,Male,Hubli,55.0,60.0,58.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400

In [37]:
df['New value']=df['value'].apply(lambda x:x*2)
df.head()

,Dataset,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance,...,Rating,PaymentMethod,Temperature,Humidity,Rainfall,WindSpeed,Condition,value,value_new,New value
0,STUDENT,1.0,Tanu,21.0,Female,Bangalore,85.0,90.0,78.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400,NaN
1,STUDENT,2.0,Bhanu,19.0,Male,Shimoga,72.0,68.0,80.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400,NaN
2,STUDENT,3.0,Sanju,23.0,Male,Mysore,90.0,95.0,88.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400,NaN
3,STUDENT,4.0,Priya,20.0,Female,Bangalore,65.0,70.0,75.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400,NaN
4,STUDENT,5.0,Ravi,22.0,Male,Hubli,55.0,60.0,58.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400,NaN

In [38]:
## Data Aggregation and Grouping
df.head()

,Dataset,StudentID,Name,Age,Gender,City,Math,Science,English,Attendance,...,Rating,PaymentMethod,Temperature,Humidity,Rainfall,WindSpeed,Condition,value,value_new,New value
0,STUDENT,1.0,Tanu,21.0,Female,Bangalore,85.0,90.0,78.0,95.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400,NaN
1,STUDENT,2.0,Bhanu,19.0,Male,Shimoga,72.0,68.0,80.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400,NaN
2,STUDENT,3.0,Sanju,23.0,Male,Mysore,90.0,95.0,88.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400,NaN
3,STUDENT,4.0,Priya,20.0,Female,Bangalore,65.0,70.0,75.0,80.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400,NaN
4,STUDENT,5.0,Ravi,22.0,Male,Hubli,55.0,60.0,58.0,70.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57400,NaN

In [39]:
group_mean=df.groupby('Name')['Age'].mean()
print(group_mean)

Name
Arun     38.000000
Bhanu    27.666667
Divya    27.000000
Kiran    45.000000
Priya    24.000000
Ravi     25.000000
Sanju    35.333333
Sneha    32.000000
Tanu     21.000000
Name: Age, dtype: float64

In [40]:
grouped_sum=df.groupby(['Name','Gender'])['Age'].sum()
print(grouped_sum)

Name   Gender
Arun   Male       38.0
Bhanu  Male       83.0
Divya  Female     27.0
Kiran  Male       45.0
Priya  Female     72.0
Ravi   Male      100.0
Sanju  Male      106.0
Sneha  Female     32.0
Tanu   Female     63.0
Name: Age, dtype: float64

In [9]:
## aggregate multiple function

grouped_agg=df.groupby('Name')['value'].agg(['mean','sum','max'])
grouped_agg

NameError: name 'df' is not defined

In [12]:
## Merging and joining dataframes
## create sample data frames
import pandas as pd
df1 = pd.DataFrame({'key':['A','B','C'],'value1':[1,2,3]})
df2 = pd.DataFrame({'key':['A','B','D'],'value2':[4,5,6]})

In [13]:
df2

  key  value2
0   A       4
1   B       5
2   D       6

In [14]:
df1

  key  value1
0   A       1
1   B       2
2   C       3

In [15]:
## Merge Dat frames on the 'key columns'8.1-numpy.ipynb
pd.merge(df1,df2,on="key",how="inner")

  key  value1  value2
0   A       1       4
1   B       2       5

In [16]:
pd.merge(df1,df2,on="key",how="outer")

  key  value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [17]:
pd.merge(df1,df2,on="key",how="left")

  key  value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [18]:
pd.merge(df1,df2,on="key",how="right")

  key  value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

hello